name: Deploy to OVH

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: collection_manager_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, openssl, tokenizer, json, bcmath, fileinfo
        coverage: none

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Configure database for testing
      run: |
        php artisan config:cache
        php artisan config:set database.connections.mysql.host 127.0.0.1
        php artisan config:set database.connections.mysql.port 3306
        php artisan config:set database.connections.mysql.database collection_manager_test
        php artisan config:set database.connections.mysql.username root
        php artisan config:set database.connections.mysql.password password

    - name: Run tests
      run: php artisan test

  deploy-ovh:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, openssl, tokenizer, json, bcmath, fileinfo
        coverage: none

    - name: Install dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate key
      run: php artisan key:generate

    - name: Directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run OVH deployment script
      run: |
        chmod +x deploy-ovh.sh
        ./deploy-ovh.sh

    - name: Deploy to OVH via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.OVH_FTP_SERVER }}
        username: ${{ secrets.OVH_FTP_USERNAME }}
        password: ${{ secrets.OVH_FTP_PASSWORD }}
        local-dir: ./
        server-dir: ${{ secrets.OVH_SERVER_DIR }}
        exclude: |
          **/.git*
          **/.git*/
          **/node_modules/**
          **/tests/**
          **/.github/**
          **/deploy-ovh.sh
          **/.env.example
          **/README.md
          **/README_STAP5.md
          **/DEPLOYMENT_OVH.md
          **/OVH_DEPLOYMENT_SUMMARY.md
          **/vendor/**

    - name: Execute post-deployment commands on OVH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.OVH_SSH_HOST }}
        username: ${{ secrets.OVH_SSH_USER }}
        key: ${{ secrets.OVH_SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.OVH_DEPLOY_PATH }}
          
          # Run OVH-specific deployment commands
          chmod +x deploy-ovh.sh
          ./deploy-ovh.sh
          
          # Set OVH-specific permissions
          chmod -R 755 storage bootstrap/cache
          chmod -R 775 storage/logs
          chmod -R 775 storage/framework/cache
          chmod -R 775 storage/framework/sessions
          chmod -R 775 storage/framework/views
          
          # Clear caches
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan cache:clear
          
          # Re-cache for production
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan optimize
          
          echo "OVH deployment completed successfully!"

  deploy-ovh-ftp-only:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, openssl, tokenizer, json, bcmath, fileinfo
        coverage: none

    - name: Install dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate key
      run: php artisan key:generate

    - name: Directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Optimize for production
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        php artisan optimize

    - name: Deploy to OVH via FTP (FTP-only hosting)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.OVH_FTP_SERVER }}
        username: ${{ secrets.OVH_FTP_USERNAME }}
        password: ${{ secrets.OVH_FTP_PASSWORD }}
        local-dir: ./
        server-dir: ${{ secrets.OVH_SERVER_DIR }}
        exclude: |
          **/.git*
          **/.git*/
          **/node_modules/**
          **/tests/**
          **/.github/**
          **/deploy-ovh.sh
          **/.env.example
          **/README.md
          **/README_STAP5.md
          **/DEPLOYMENT_OVH.md
          **/OVH_DEPLOYMENT_SUMMARY.md
          **/vendor/**
        dangerous-clean-slate: true 